package com.pojo;
// Generated Aug 11, 2016 9:21:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private Date birthdate;

    public Contact() {
    }

    public Contact(String name, String password, Date birthdate) {
       this.name = name;
       this.password = password;
       this.birthdate = birthdate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }




}


